keys:
  - &users:
    - &user C2FD2F276EB035F4CBB4660E2228A8900567AE95
  - &hosts:
    - &thinkpadx1 age1auuwgpv960wg3akpxec49xvyntrxfs90l85zygu95rh7xjagzeysze5u2u
    - &asrock age1auuwgpv960wg3akpxec49xvyntrxfs90l85zygu95rh7xjagzeysze5u2u  # Garbage

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *thinkpadx1
        pgp:
          - *user
